services:
#    train.example:
#        class: TrainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    train.trainline_manager:
        class: TrainBundle\Service\TrainlineManager
        arguments: ["@mailer", "@templating", "@doctrine.orm.entity_manager", "@logger"]

    form.trip:
        class: TrainBundle\Form\TripType
        arguments: ["@router"]
        tags:
            - { name: form.type }
